---
title: "fun_model"
output: html_document
---

```{r}
library(funModeling)
library(readr)
library(tidyr)
library(dplyr)
```



```{r}
cars <- read_csv("vehicle_data/car_prices.csv")
```


```{r}
status(cars)
```


```{r}
cars<-drop_na(cars)
```




```{r}
cars <- cars %>%
    mutate(body = replace(body, (body == 'SUV'| body == 'suv'), 'SUV')) %>%
    mutate(body = replace(body, body == "Coupe" | body=='Elantra Coupe' |body=='G37 Coupe'| body=='Q60 Coupe'| body=='g coupe'| body=='cts coupe'|body=='elantra coupe'|body=='G Coupe'|body=='Genesis Coupe'|body=='genesis coupe'|body=='q60 coupe'|body=='CTS Coupe'|body=='Koup'|body=='koup'|body=='CTS-V Coupe'|body=='coupe'|body=='cts-v coupe' ,"Coupe"))%>%
    mutate(body = replace(body, body == "Crew Cab"|body=='Access Cab'|body=='SuperCrew'|body=='SuperCab'|body=='Regular Cab'|body=='Xtracab'|body=='xtracab'|body=='regular-cab'|body=='supercrew'|body=='crew cab'|body=='regular cab'|body=='supercab'|body=='double cab'|body=='mega cab'|body=='Double Cab'|body=='King Cab'|body=='Quad Cab'|body=='Mega Cab'|body=='Cab Plus'|body=='quad cab'|body=='extended cab'|body=='CrewMax Cab'|body=='Extended Cab'|body=='Club Cab'|body=='king cab'|body=='crewmax cab'|body=='access cab'|body=='club cab'|body=='Cab Plus 4'|body=='cab plus 4', "Cab"))%>%mutate(body = replace(body, (body == "Van" | body == "Promaster Cargo Van"|body=='minivan'|body=='transit van'|body=='promaster cargo van'|body=='E-Series Van'|body=='Ram Van'|body=='Transit Van'|body=='Minivan'|body=='van'|body=='e-series van'|body==''), "Van"))%>%mutate(body = replace(body, (body == "sedan"|body=='Sedan'|body=='G Sedan'|body=='g sedan'),"Sedan"))%>%mutate(body = replace(body, (body == 'G Convertible'|body=='G37 Convertible'|body=='Q60 Convertible'|body=='Beetle Convertible'|body=='g convertible'|body=='granturismo convertible'|body=='q60 convertible'|body=='Convertible'|body=='GranTurismo Convertible'|body=='convertible'|body=='g37 convertible'|body=='beetle convertible'),"Convertible"))%>%mutate(body=replace(body,body=='Hatchback'|body=='hatchback','Hatchback'))%>%mutate(body=replace(body,(body=='CTS Wagon'|body=='TSX Sport Wagon'|body=='CTS-V Wagon'|body=='wagon'|body=='tsx sport wagon'|body=='cts wagon'),'Wagon'))
```




```{r}
plot_num(cars,bins=100)

```





```{r}
profiling_num(cars)
```



```{r}
transmission<-cars%>%select(transmission)
freq(transmission)

```



```{r}
body<-cars%>%select(body)
freq(body)

```




```{r}
correlation_table(cars,"sellingprice")
```




```{r}
var_rank_info(cars,"sellingprice")
```


```{r}
plotar(data=cars, input = c("condition", "mmr","odometer","year","sellingprice"), target="transmission", plot_type="boxplot")

```



```{r}
plotar(data=cars, input = c("condition", "mmr","odometer","year","sellingprice"), target="body", plot_type="boxplot")
```




```{r}
plotar(data=cars, input = c("condition", "mmr","odometer","year","sellingprice"), target="body", plot_type="histdens")

```




```{r}
tukey_outlier(cars$sellingprice)
hampel_outlier(cars$sellingprice)

```

